services:
  - type: web
    name: buxinstore
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout=120
    releaseCommand: python -m flask db upgrade
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: wsgi.py

